.ALIASES
V_VDD           VDD(+=VDD -=0 ) CN @I-FFD-01.SCHEMATIC1(sch_1):INS41356@SOURCE.VDC.Normal(chips)
M_M1            M1(d=N41218 g=VDD s=N41234 b=0 ) CN @I-FFD-01.SCHEMATIC1(sch_1):INS41132@BREAKOUT.MbreakN.Normal(chips)
M_M2            M2(d=N41218 g=VDD s=VDD b=VDD ) CN @I-FFD-01.SCHEMATIC1(sch_1):INS41152@BREAKOUT.MbreakP.Normal(chips)
M_M3            M3(d=N41218 g=0 s=VDD b=VDD ) CN @I-FFD-01.SCHEMATIC1(sch_1):INS41172@BREAKOUT.MbreakP.Normal(chips)
M_M4            M4(d=N41234 g=0 s=0 b=0 ) CN @I-FFD-01.SCHEMATIC1(sch_1):INS41196@BREAKOUT.MbreakN.Normal(chips)
_    _(VDD=VDD)
_    _(GND_0=0)
.ENDALIASES
