.ALIASES
M_M2            M2(d=N14558 g=N14658 s=0 b=0 ) CN @COMPARADOR.rama(sch_1):INS14457@BREAKOUT.MbreakN.Normal(chips)
M_M1            M1(d=N14558 g=N14603 s=N14603 b=N14603 ) CN @COMPARADOR.rama(sch_1):INS14425@BREAKOUT.MbreakP.Normal(chips)
V_V1            V1(+=N14658 -=0 ) CN @COMPARADOR.rama(sch_1):INS14571@SOURCE.VDC.Normal(chips)
V_V2            V2(+=N14603 -=0 ) CN @COMPARADOR.rama(sch_1):INS14587@SOURCE.VDC.Normal(chips)
_    _(GND_0=0)
.ENDALIASES
