.ALIASES
V_V1            V1(+=N29931 -=0 ) CN @I-NAND.NEG(sch_1):INS92384@SOURCE.VDC.Normal(chips)
M_M5            M5(d=N29915 g=N29941 s=N29931 b=N29931 ) CN @I-NAND.NEG(sch_1):INS29979@BREAKOUT.MbreakP.Normal(chips)
V_V2            V2(+=N29941 -=0 ) CN @I-NAND.NEG(sch_1):INS92412@SOURCE.VDC.Normal(chips)
M_M6            M6(d=N29915 g=N29941 s=0 b=0 ) CN @I-NAND.NEG(sch_1):INS30013@BREAKOUT.MbreakN.Normal(chips)
.ENDALIASES
