.ALIASES
V_VDD           VDD(+=N29931 -=0 ) CN @I-NAND.NEG(sch_1):INS88456@SOURCE.VDC.Normal(chips)
V_Vin           Vin(+=IN -=0 ) CN @I-NAND.NEG(sch_1):INS90211@SOURCE.VPULSE.Normal(chips)
M_M5            M5(d=OUT g=IN s=N29931 b=N29931 ) CN @I-NAND.NEG(sch_1):INS29979@BREAKOUT.MbreakP.Normal(chips)
M_M6            M6(d=OUT g=IN s=0 b=0 ) CN @I-NAND.NEG(sch_1):INS30013@BREAKOUT.MbreakN.Normal(chips)
_    _(OUT=OUT)
_    _(IN=IN)
.ENDALIASES
