.ALIASES
V_IN2           IN2(+=N27481 -=0 ) CN @I-FFD.TEST NAND-3(sch_1):INS28224@SOURCE.VPULSE.Normal(chips)
M_M1            M1(d=OUT g=N27521 s=N27469 b=N27469 ) CN @I-FFD.TEST NAND-3(sch_1):INS27299@BREAKOUT.MbreakN.Normal(chips)
M_M5            M5(d=OUT g=N27297 s=N27449 b=N27449 ) CN @I-FFD.TEST NAND-3(sch_1):INS27555@BREAKOUT.MbreakP.Normal(chips)
M_M2            M2(d=N27469 g=N27481 s=N27495 b=N27495 ) CN @I-FFD.TEST NAND-3(sch_1):INS27333@BREAKOUT.MbreakN.Normal(chips)
V_VDD           VDD(+=N27449 -=0 ) CN @I-FFD.TEST NAND-3(sch_1):INS28071@SOURCE.VDC.Normal(chips)
V_IN3           IN3(+=N27297 -=0 ) CN @I-FFD.TEST NAND-3(sch_1):INS28302@SOURCE.VPULSE.Normal(chips)
M_M3            M3(d=OUT g=N27521 s=N27449 b=N27449 ) CN @I-FFD.TEST NAND-3(sch_1):INS27367@BREAKOUT.MbreakP.Normal(chips)
M_M6            M6(d=N27495 g=N27297 s=0 b=0 ) CN @I-FFD.TEST NAND-3(sch_1):INS27613@BREAKOUT.MbreakN.Normal(chips)
M_M4            M4(d=OUT g=N27481 s=N27449 b=N27449 ) CN @I-FFD.TEST NAND-3(sch_1):INS27405@BREAKOUT.MbreakP.Normal(chips)
V_IN1           IN1(+=N27521 -=0 ) CN @I-FFD.TEST NAND-3(sch_1):INS28146@SOURCE.VPULSE.Normal(chips)
_    _(OUT=OUT)
.ENDALIASES
