.ALIASES
M_M1            M1(d=N14473 g=N14405 s=N00155 b=0 ) CN @COMPARADOR.comparador(sch_1):INS30@BREAKOUT.MbreakN.Normal(chips)
M_M2            M2(d=N15666 g=N17944 s=N00155 b=0 ) CN @COMPARADOR.comparador(sch_1):INS50@BREAKOUT.MbreakN.Normal(chips)
M_M3            M3(d=N00155 g=N14299 s=0 b=0 ) CN @COMPARADOR.comparador(sch_1):INS70@BREAKOUT.MbreakN.Normal(chips)
M_M4            M4(d=N14473 g=N14473 s=N14416 b=N14416 ) CN @COMPARADOR.comparador(sch_1):INS103@BREAKOUT.MbreakP.Normal(chips)
M_M5            M5(d=N15666 g=N14473 s=N14416 b=N14416 ) CN @COMPARADOR.comparador(sch_1):INS123@BREAKOUT.MbreakP.Normal(chips)
V_V1            V1(+=N14405 -=0 ) CN @COMPARADOR.comparador(sch_1):INS188@SOURCE.VDC.Normal(chips)
V_V3            V3(+=N14299 -=0 ) CN @COMPARADOR.comparador(sch_1):INS220@SOURCE.VDC.Normal(chips)
V_V4            V4(+=N14416 -=0 ) CN @COMPARADOR.comparador(sch_1):INS236@SOURCE.VDC.Normal(chips)
V_V2            V2(+=N17944 -=0 ) CN @COMPARADOR.comparador(sch_1):INS19517@SOURCE.VDC.Normal(chips)
M_M6            M6(d=N20369 g=N15666 s=N14416 b=N14416 ) CN @COMPARADOR.comparador(sch_1):INS20168@BREAKOUT.MbreakP.Normal(chips)
M_M7            M7(d=N20369 g=N20575 s=0 b=0 ) CN @COMPARADOR.comparador(sch_1):INS20230@BREAKOUT.MbreakN.Normal(chips)
V_V5            V5(+=N20575 -=0 ) CN @COMPARADOR.comparador(sch_1):INS21545@SOURCE.VDC.Normal(chips)
.ENDALIASES
